export const PRIMES_REQUESTED = 'PRIMES_REQUESTED';
export const PRIMES_RECEIVED = 'GET_RECEIVED';

export const LAST_PAGE_REQUESTED = 'LAST_PAGE_REQUESTED';
export const LAST_PAGE_RECEIVED = 'LAST_PAGE_RECEIVED';

export const SET_MAX = 'SET_MAX';
export const SET_PAGE = 'SET_PAGE';
